# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('qualification', models.CharField(max_length=1000)),
                ('reg_no', models.IntegerField()),
                ('pt_ref', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('composition', models.CharField(max_length=1000)),
                ('exp_date', models.DateField()),
                ('manu_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nonmedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('exp_date', models.DateField()),
                ('manu_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('loc', models.CharField(max_length=1000)),
            ],
        ),
    ]
