# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_medicines_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonmedicine',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonmedicine',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
