# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_auto_20170323_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
